### ISSUE TITLE
Builder role kickstart ISO inject fails from duplicate error

### ISSUE THREAD

**Issue by zjpeterson** [redhat-cop/infra.osbuild#123]
When using `builder_compose_type=edge-installer`, I get a failure from `mkksiso` that the ISO already exists:
```
ERROR: Command 'mkksiso /var/www/html/ansible_edge/kickstart.ks /tmp/ansible_edge/ansible_edge-0.0.1.iso /tmp/ansible_edge/ansible_edge-0.0.1.iso' failed with return code: 1 and error message, 'ERROR:/tmp/ansible_edge/ansible_edge-0.0.1.iso already exists\nERROR:Problems running /bin/mkksiso\n'"
```

If I change the role code here: https://github.com/redhat-cop/infra.osbuild/blob/d5aed5f6978df6c6943b3fc317db0aa02149b270/roles/builder/tasks/main.yml#L211-L220
using a different temporary filename on lines 215 and 219 (I just put a `_ks` at the end) then it succeeds. Should lines 214 and 215 really be identical?

**Comment by matoval** [comment]
@zjpeterson We are having trouble reproducing this issue. Do you have anymore information on how to reproduce this issue?
