### ISSUE TITLE
[Feature Request] Modify setup_server role to use repositories from Red Hat Satellite

### ISSUE THREAD

**Issue by adworjan** [redhat-cop/infra.osbuild#129]
Currently, the setup_server role is only designed to work with the Red Hat CDN which does not work in disconnected environments or with hosts registered to Red Hat Satellite.

Request an additional role, or variable to allow setting up the built-in repositories and cert to use RH Satellite

Working Example:
https://github.com/shadowman-lab/Ansible-ImageBuilder/tree/main/roles/image_builder_setup_sat

**Comment by chadmf** [comment]
This should work the same as any customer repository.

**Comment by adworjan** [comment]
That's only true for additional repositories, not the default base and app stream repos:

https://access.redhat.com/solutions/5773421

**Comment by matoval** [comment]
@adworjan I made a PR to resolve this issue: https://github.com/redhat-cop/infra.osbuild/pull/271
Can you take a second look at it?
