### ISSUE TITLE
Issue on command ansible-playbook playbooks/osbuild_builder.yml

### ISSUE THREAD

**Issue by bdherouville** [redhat-cop/infra.osbuild#146]
Hi,

the command ansible-playbook playbooks/osbuild_builder.yml fails with this error :

TASK [infra.osbuild.builder : Create a blueprint] ********************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: Value of unknown type: <class 'AttributeError'>, 'Weldr' object has no attribute 'toml'
fatal: [imagebuilder.localdomain]: FAILED! => {"changed": false, "module_stderr": "Shared connection to imagebuilder.localdomain closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_infra.osbuild.create_blueprint_payload_ncqwucdh/ansible_infra.osbuild.create_blueprint_payload.zip/ansible_collections/infra/osbuild/plugins/modules/create_blueprint.py\", line 197, in create_blueprint\r\nAttributeError: 'Weldr' object has no attribute 'toml'\r\n\r\nDuring handling of the above exception, another exception occurred:\r\n\r\nTraceback (most recent call last):\r\n  File \"/home/adminlocal/.ansible/tmp/ansible-tmp-1682093377.3102357-2641-14401642249096/AnsiballZ_create_blueprint.py\", line 107, in <module>\r\n    _ansiballz_main()\r\n  File \"/home/adminlocal/.ansible/tmp/ansible-tmp-1682093377.3102357-2641-14401642249096/AnsiballZ_create_blueprint.py\", line 99, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/home/adminlocal/.ansible/tmp/ansible-tmp-1682093377.3102357-2641-14401642249096/AnsiballZ_create_blueprint.py\", line 48, in invoke_module\r\n    run_name='__main__', alter_sys=True)\r\n  File \"/usr/lib64/python3.6/runpy.py\", line 205, in run_module\r\n    return _run_module_code(code, init_globals, run_name, mod_spec)\r\n  File \"/usr/lib64/python3.6/runpy.py\", line 96, in _run_module_code\r\n    mod_name, mod_spec, pkg_name, script_name)\r\n  File \"/usr/lib64/python3.6/runpy.py\", line 85, in _run_code\r\n    exec(code, run_globals)\r\n  File \"/tmp/ansible_infra.osbuild.create_blueprint_payload_ncqwucdh/ansible_infra.osbuild.create_blueprint_payload.zip/ansible_collections/infra/osbuild/plugins/modules/create_blueprint.py\", line 218, in <module>\r\n  File \"/tmp/ansible_infra.osbuild.create_blueprint_payload_ncqwucdh/ansible_infra.osbuild.create_blueprint_payload.zip/ansible_collections/infra/osbuild/plugins/modules/create_blueprint.py\", line 214, in main\r\n  File \"/tmp/ansible_infra.osbuild.create_blueprint_payload_ncqwucdh/ansible_infra.osbuild.create_blueprint_payload.zip/ansible_collections/infra/osbuild/plugins/modules/create_blueprint.py\", line 200, in create_blueprint\r\n  File \"/tmp/ansible_infra.osbuild.create_blueprint_payload_ncqwucdh/ansible_infra.osbuild.create_blueprint_payload.zip/ansible/module_utils/basic.py\", line 1533, in fail_json\r\n  File \"/tmp/ansible_infra.osbuild.create_blueprint_payload_ncqwucdh/ansible_infra.osbuild.create_blueprint_payload.zip/ansible/module_utils/basic.py\", line 1506, in _return_formatted\r\n  File \"/tmp/ansible_infra.osbuild.create_blueprint_payload_ncqwucdh/ansible_infra.osbuild.create_blueprint_payload.zip/ansible/module_utils/common/parameters.py\", line 928, in remove_values\r\n  File \"/tmp/ansible_infra.osbuild.create_blueprint_payload_ncqwucdh/ansible_infra.osbuild.create_blueprint_payload.zip/ansible/module_utils/common/parameters.py\", line 471, in _remove_values_conditions\r\nTypeError: Value of unknown type: <class 'AttributeError'>, 'Weldr' object has no attribute 'toml'\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

**Comment by bprins** [comment]
This seems to be fixed by installing `python3-pytoml` on EL8 or `python3-toml` on EL9 (see the `setup_server` role).

**Comment by resoluteCoder** [comment]
That seems to be correct. We have those packages baked into the `setup_server` here https://github.com/redhat-cop/infra.osbuild/blob/main/roles/setup_server/tasks/main.yaml#L54 and https://github.com/redhat-cop/infra.osbuild/blob/main/roles/setup_server/tasks/main.yaml#L67

Let me know if the problem persists

**Comment by chadmf** [comment]
issue fixed when you run the setup role
