### ISSUE TITLE
BUG - RHSM repositories

### ISSUE THREAD

**Issue by oglok** [redhat-cop/infra.osbuild#226]
In order to add packages to an image that are located in repos that require a Red Hat subscription, the build host does NOT need to have those repositories enabled in the host. This requirement is self-imposed:

```
Error msg:

    ],
    "results": [
        "Repository 'rhocp-4.13-for-rhel-9-x86_64-rpms' is disabled for this system"
    ]
}

    "results": [
        "Repository 'fast-datapath-for-rhel-9-x86_64-rpms' is disabled for this system"
    ]
```

It is enough to add the repo as an osbuild source with the param `rhsm: true`.

A proof of this, is that you can build a RHEL 8 image using the blueprint param `distro = rhel-8` in a RHEL 9 build host. If this self-imposed requirement were true, the user could not enable a RHEL8 repository in a RHEL9 host.

**Comment by matoval** [comment]
@oglok After looking through the code, it looks like we aren't enabling the RHSM repos. We are only setting the rhsm property to true.

**Comment by chadmf** [comment]
related to #129

**Comment by chadmf** [comment]
Just need to document setting up satellite repos like any other custom repos.
