### ISSUE TITLE
RFE - Gather logs from OSBUILD

### ISSUE THREAD

**Issue by oglok** [redhat-cop/infra.osbuild#227]
If a build fails, there is no logs or information provided by the collection to know why it has failed. 
For example, if you add some kernel customizations to the builder_compose_customizations ansible var:

```
builder_compose_customizations:
  kernel:
    append: "nomst=force"
```

and try to build an ostree image, osbuild composer will fail. 
The only way to know what happened is to ssh into the build host, and check the journal for osbuild-composer service.

**Comment by chadmf** [comment]
Should not be much work to add a if fail collect log routine.

**Comment by resoluteCoder** [comment]
The builder role will return logs on anything osbuild composer related
