### ISSUE TITLE
Cleanup to follow Ansible good practices

### ISSUE THREAD

**Issue by chadmf** [redhat-cop/infra.osbuild#24]
##### SUMMARY
Move all code into roles when possible. Example in playbooks/osbuild_image_server.yml we have some directory configuration, that should be moved to the role.

Any tasks that are a one time like user creation we should add to the build_server role. Example we add the user to the weldr group on every run of the testbuild.yml

Testbuild should most likely be migrated to a role called build as it has variables we need to set for things like ssh_key_path.

**Comment by maxamillion** [comment]
@chadmf I think we're in pretty good shape, we've been slowly chasing the guidelines from https://github.com/redhat-cop/automation-good-practices/blob/main/roles/README.adoc and I think as it stands now we're good.

**Comment by chadmf** [comment]
./agree feel free to close
