### ISSUE TITLE
Updating README install information

### ISSUE THREAD

**Issue by alisonlhart** [redhat-cop/infra.osbuild#251]
This section https://github.com/redhat-cop/infra.osbuild#installing in the README needs to be updated with the correct install information. 

Since the collection is now on Automation Hub, instead of installing from `ansible-galaxy collection install git+https://github.com/redhat-cop/infra.osbuild`, install directly with the collection name: `ansible-galaxy collection install infra.osbuild`. 

Any other install references (if relevant) should be updated in the same way. 

If there is no upcoming release planned to Automation Hub, please make a one-off minor release for this fix, so customers can receive the updated docs as soon as possible.

**Comment by resoluteCoder** [comment]
Sounds good :smile:

**Comment by resoluteCoder** [comment]
Uploaded to automation hub
