### ISSUE TITLE
Image tracking and patching

### ISSUE THREAD

**Issue by chadmf** [redhat-cop/infra.osbuild#28]
##### SUMMARY
Having the ability to see what versions of an image endpoints are running and push new versions to the endpoints would be a great feature for this collection.

##### ISSUE TYPE
- Feature Idea

**Comment by maxamillion** [comment]
> ##### SUMMARY
> 
> Having the ability to see what versions of an image endpoints are running and push new versions to the endpoints would be a great feature for this collection.
> ##### ISSUE TYPE
> 
>     * Feature Idea
 
Would this just be a fact module? ... or $other?
