### ISSUE TITLE
2.2.0 missing from galaxy?

### ISSUE THREAD

**Issue by sean-m-sullivan** [redhat-cop/infra.osbuild#297]
With the galaxy changeover there appear to be missing versions of your collection on galaxy. 
https://galaxy.ansible.com/ui/repo/published/infra/osbuild/

Lastest is 2.1.0, and 2.2.0 is on console.redhat.com

Not sure how you want to fix it, just uploading latest, or uploading the last few releases. You should be able to do it the normal way. However if you want me to upload some versions in a particular order, let me know and I can take care of that.

I am not seeing the 2.2.0 tagged here, so maybe it isn't an error, but let me know if I can assist either way.

**Comment by matoval** [comment]
@sean-m-sullivan I just added the tag for 2.2.0. Thank you for updating Galaxy.
