### ISSUE TITLE
/tmp/blueprint.toml key in customizations file is a path not a key

### ISSUE THREAD

**Issue by chadmf** [redhat-cop/infra.osbuild#40]
##### SUMMARY
The template that the builder role ie. roles/builder/tasks/main.yml creates needs to read in the local pub key and put it into the toml like this: 

key: "{{ lookup('file', {{ pub_key) }}"

Currently the file creates witht he variable assigned to pub key:
```

[[customizations.user]]
name = "core"
description = "test user"
password = "openshift"
key = "~/.ssh/id_rsa.pub"
groups = ["users", "wheel"]
```

##### ISSUE TYPE
- Bug Report

**Comment by matoval** [comment]
This issue is now resolved
