### ISSUE TITLE
Image Builder on RHEL8 Requires python36

### ISSUE THREAD

**Issue by jjaswanson4** [redhat-cop/infra.osbuild#72]
See this kb article: https://access.redhat.com/solutions/6973651

tl;dr: if you get the error: `FileNotFoundError: [Errno 2] No such file or directory: '/run/osbuild/bin/org.osbuild.rpm': '/run/osbuild/bin/org.osbuild.rpm'`

Run: `dnf install python36`

We'll need to install that package in the setup_server role

**Comment by maxamillion** [comment]
RHEL 8.3 has been EOL for over a year, it wasn't even an EUS release and even if it was then it would still be EOL by now.

https://access.redhat.com/support/policy/updates/errata#RHEL8_and_9_Life_Cycle

**Comment by jjaswanson4** [comment]
> Red Hat Enterprise Linux >= 8.3
Meaning, this affects RHEL8.[3-7]

I confirmed this behavior on a RHEL8.7 box earlier today

**Comment by maxamillion** [comment]
@jjaswanson4 I find it odd that it's not affecting the three versions of RHEL 8.x that we're testing in CI, but alright ... I suppose we can handle that in the role.

cc @resoluteCoder

**Comment by jjaswanson4** [comment]
I'm using RHEL8 in AWS, not sure if we ship a different package set there?

python36 is available from RHUI so it _shouldn't_ be an issue anywhere to check for it/install it.

**Comment by jjaswanson4** [comment]
Upon some further digging, the package set on AWS BYOS instances is super minimal (as in: doesn't even ship with _firewalld_), so I'm no longer surprised to be hitting this.
