### ISSUE TITLE
Remove custom repos after the image using the custom repo is built

### ISSUE THREAD

**Issue by matoval** [redhat-cop/infra.osbuild#92]
We should remove custom repos after the image using the custom repo is built so we can avoid conflicts.

Background:
When the microshift repos are added as sources and we try to build a non microshift image we are getting a conflict error:
```
file /usr/share/redhat-release/EULA conflicts between attempted installs of redhat-release-eula-8.7-0.3.el8.x86_64 and redhat-release-coreos-410.84-2.el8.x86_64

```

Remove the microshift sources resolve this issue and there doesn't seem to be an negative in adding and removing custom repos every time they are needed.

**Comment by maxamillion** [comment]
@matoval I think we currently do this for custom repos, but do not for the subscription manager repos. Yes?

**Comment by matoval** [comment]
Looks like this issue was caused by a build failing and Ansible exited out before disabling the custom repos. Issue #97 was created to address cleaning up custom repos if a build fails.
