### ISSUE TITLE
rpm-ostree upgrade --check crashes when using the collection to update the remote OSTree repo

### ISSUE THREAD

**Issue by luisarizmendi** [redhat-cop/infra.osbuild#94]
This is more an rpm-ostree issue [1] but I add this comment here for awareness because the issue appeared because of how the collection generates the published ostree repo in the HTTP.

This issue will affect people using the Collection to generate new images and using the OSTree repo on the Image Builder from remote ostree systems.

The Collection generates an ostree repo and commit changes to it when new image versions are generated, which is would be the right approach instead of just untar the file and copy the files into the HTTP), but if you use this HTTP repo as an ostree *remote repo* in the OSTree system, and you update the image, the rpm-ostree crashes when you run `rpm-ostree upgrade --check`.

If instead of creating an ostree repo in the HTTP server, you just copy the files out from the TAR file, the problem does not appear.

More information about the issue and how to reproduce it can be found here: [2]

[1] https://github.com/coreos/rpm-ostree/issues/4280
[2] https://github.com/luisarizmendi/bugs

**Comment by resoluteCoder** [comment]
@luisarizmendi I have ran into this issue before. +1

**Comment by chadmf** [comment]
Can we just document this and close?

**Comment by chadmf** [comment]
Make a FAQ at end of readme
